server:
  port: 9003



spring:
  cloud:
    kubernetes:
      secrets:
        enableApi: true
    config:
      server:
        composite:
          - type: kubernetes
            secrets:
              name: my-secret
              namespace: default



